version: "3"
services:
  app:
    build: .
    depends_on:
      - redis
      - algae
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis
      - ALGAE_IMAGE_NAME=dexterleng/algae@sha256:8710ce133fd41f410c9d78346c3d38cd1976c15658873a164621d5459781743e
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/usr/src/app
    ports:
      - 8080:8080
  redis:
    image: redis:alpine3.11 
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
  algae:
    image: dexterleng/algae@sha256:8710ce133fd41f410c9d78346c3d38cd1976c15658873a164621d5459781743e

